name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install requests

      - name: Set version and update info.json
        run: |
          commit_count=$(git rev-list --count main)
          echo "COMMITS_SINCE_LAST_TAG=$commit_count" >> $GITHUB_ENV
          echo "Commits since last tag: $commit_count"

          # Replace version in info.json
          sed -i 's|  "version": .*,|  "version": "1.0.$commit_count"|g' info.json

      - name: Zip files excluding .py files
        run: |
          mkdir H-QoL-FF-1.0.$commit_count
          find . -type f -not -name "*.py" -exec cp {} H-QoL-FF-1.0.$commit_count \;
          zip -r H-QoL-FF-1.0.$commit_count.zip H-QoL-FF-1.0.$commit_count
          rm -rf H-QoL-FF-1.0.$commit_count

      - name: Upload zip file using Python script
        env:
          MOD_UPLOAD_API_KEY: ${{ secrets.MOD_UPLOAD_API_KEY }}
          MOD_UPLOAD_NAME: "H-Qol-FF"
          MOD_UPLOAD_FILE: "./H-QoL-FF-1.0.$commit_count.zip"
        run: python upload_script.py
